

export const authors = 
  [{
    id: 1,
    realName: "John Lovell",
    penName: "John Lovell",
    email: "johnlovell@live.co.uk",
    phoneNumber: "07780644003",
    location: "Wales",
    address1: "LongFields",
    address2: "Buck Road",
    address3: "Commonwood",
    address4: "Wrexham",
    postCode: "LL139TF",
    sortCode: "110757",
    accountNo: "00336899",
    retainedClient: false,
    gender: "M",
    notes: "Warm, Informal, Splurge, Might be picky, Occasionally needs prompting, Comprehends things well"
  },
    {
      id: 2,
      realName: "David Gibson",
      penName: "David Gibson",
      email: "gibsonad@msn.com",
      phoneNumber: "",
      location: "Wales",
      address1: "Chapel Street",
      address2: "Rhostyllen",
      address3: "Wrexham",
      address4: "Clwyd",
      postCode: "LL14 4AS",
      sortCode: "30-99-95",
      accountNo: "34202560",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      id: 3,
      realName: "Michelle Path",
      penName: "Michelle Path",
      email: "cyberfox@dcsi.net.au",
      phoneNumber: "",
      location: "Australia",
      address1: "19, Stockdales Road",
      address2: "Warragul",
      address3: "3820",
      address4: "Victoria",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: true,
      gender: "F",
      notes: "Warm, Informal, Quick responses, Savvy, Comprehends things quite well, Splurge, Not too picky\r\n\r\nAlternative address - \r\n\r\nPO Box 827\r\nWarragul\r\n3820\r\nVictoria\r\nAustralia"
    },
    {
      "Id": "69F96989-5EF6-4EA8-91F5-042370122934",
      realName: "Kate Williams",
      penName: "Kate Williams",
      email: "kate_wil2000@yahoo.com",
      phoneNumber: "01767 262714",
      location: "England",
      address1: "23, Horslow Street",
      address2: "Potton",
      address3: "Beds",
      address4: "",
      postCode: "SG19 2NS",
      sortCode: "309079",
      accountNo: "20810268",
      retainedClient: false,
      gender: "F",
      notes: ""
    }, {
      "Id": "9D44FF17-01BE-4D77-91C9-0523FF5839E3",
      realName: "David P. Philip",
      penName: "David P. Philip",
      email: "dpp.author@gmail.com",
      phoneNumber: "07503 047888",
      location: "England",
      address1: "The Annexe, Thatched Cottage",
      address2: "Barnham Road",
      address3: "Eastergate",
      address4: "Chichester",
      postCode: "PO20 3RP",
      sortCode: "60-05-24",
      accountNo: "21720568",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "4C6A0F05-5103-46BB-9FF6-05A350A54D52",
      realName: "John Davies",
      penName: "John Davies",
      email: "davies.jhndvs@btinternet.com",
      phoneNumber: "01639 881341",
      location: "Wales",
      address1: "8, Eglwys Nunydd",
      address2: "Margam",
      address3: "Port Talbot",
      address4: "",
      postCode: "SA13 2PS",
      sortCode: "40-37-18",
      accountNo: "91079409",
      retainedClient: true,
      gender: "M",
      notes: "Warm, Informal, Reasonably prompt savvy comprehension finances, Very amenable not picky. Retained author so very relaxed and warm."
    },
    {
      "Id": "8328596A-3B6F-4C7F-A0C9-069DF7439DEE",
      realName: "Tim Humphreys-Jones",
      penName: "Tim Humphreys-Jones",
      email: "preechpoetry@gmail.com",
      phoneNumber: "01978 253328, 07927 955362",
      location: "Wales",
      address1: "Flat 2, The Feathers",
      address2: "Charles St",
      address3: "Wrexham",
      address4: "",
      postCode: "LL13 8BS",
      sortCode: "55-81-42",
      accountNo: "90628918",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "20D5443E-2B42-4694-90B0-09D9601C6930",
      realName: "Sir Arthur Lawrence",
      penName: "Sir Arthur Lawrence",
      email: "Sirarthurlawrence@btinternet.com",
      phoneNumber: "02085413935",
      location: "England",
      address1: "18 Wolsey Drive",
      address2: "Kingston Upon Thames",
      address3: "",
      address4: "",
      postCode: "KT25DN",
      sortCode: "162224",
      accountNo: "10024945",
      retainedClient: false,
      gender: "M",
      notes: "Not that warm, formal, splurge, open to ideas, can be slow to respond, fairly savvy, comprehends things well"
    },
    {
      "Id": "2AF4D1B2-AB77-4F12-9F30-0A78D27E15C6",
      realName: "Sima Patel",
      penName: "Sima Patel",
      email: "simapatel04@gmail.com",
      phoneNumber: "",
      location: "United States",
      address1: "4529 Forsyth Lane",
      address2: "Grand Prairie",
      address3: "Texas",
      address4: "75052",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "72EF359B-3E3E-4DEC-A0C6-0BC7B76F7FF5",
      realName: "Beth Cortese",
      penName: "Beth Cortese",
      email: "b.cortese@lancaster.ac.uk",
      phoneNumber: "07985646003",
      location: "England",
      address1: "18, Main Road",
      address2: "Galgate",
      address3: "Lancaster",
      address4: "",
      postCode: "LA2 0JH",
      sortCode: "07-00-93",
      accountNo: "1196 486478543",
      retainedClient: true,
      gender: "F",
      notes: ""
    },
    {
      "Id": "6F323771-98AE-49DB-8148-10BD2F798090",
      realName: "Mike Stenson",
      penName: "Mike Stenson",
      email: "m.stenson147@btinternet.com",
      phoneNumber: "",
      location: "Wales",
      address1: "Lilac Cottage",
      address2: "Cross Street",
      address3: "Holt",
      address4: "Wrexham",
      postCode: "LL13 9JD",
      sortCode: "30-99-95",
      accountNo: "17335760",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "CE532A19-F515-40EE-B99E-128246F8791B",
      realName: "Emma Adams",
      penName: "Emma Adams",
      email: "memzi@live.co.uk",
      phoneNumber: "07943344159",
      location: "England",
      address1: "20, Rowheath Road",
      address2: "Cotteridge",
      address3: "Birmingham",
      address4: "",
      postCode: "B30 2EP",
      sortCode: "20-08-44",
      accountNo: "43783782",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "EA9CE68B-4D11-4A4F-A0EB-139D8B996706",
      realName: "Ryan Hoadley-Thaxter",
      penName: "R. D. Thaxter",
      email: "rdhthaxter@gmail.com",
      phoneNumber: "07731682826",
      location: "England",
      address1: "9 Bluegate",
      address2: "Godmanchester",
      address3: "Huntingdon",
      address4: "",
      postCode: "PE292EZ",
      sortCode: "20-43-63",
      accountNo: "03715272",
      retainedClient: false,
      gender: "M",
      notes: "warm, open to ideas, splurge, quick to respond, quite savvy, peppery"
    },
    {
      "Id": "6C5640B7-2BEE-4B82-803C-14B7B71EBD5B",
      realName: "Malcolm Cowper",
      penName: "Malcolm Cowper",
      email: "malcomcowper@gmail.com",
      phoneNumber: "01656 858812, 07761 498284",
      location: "Wales",
      address1: "18, Hookland Road",
      address2: "Porthcawl",
      address3: "",
      address4: "",
      postCode: "CF36 5SE",
      sortCode: "08-90-39",
      accountNo: "06401409",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "3AD82F8A-78AB-41E2-BD61-1A8BC7986968",
      realName: "Jennifer Silcox",
      penName: "Jennifer Heapes",
      email: "jennifer_heapes@hotmail.com",
      phoneNumber: "07746136102",
      location: "England",
      address1: "10, The Pines",
      address2: "Horsham",
      address3: "West Sussex",
      address4: "",
      postCode: "RH12 4UF",
      sortCode: "11-13-19",
      accountNo: "00275815",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "FB3B046D-AE5C-4D54-94DF-1C8723168325",
      realName: "Mick Roberts",
      penName: "Michael Roberts",
      email: "mick.roberts93@googlemail.com",
      phoneNumber: "07501 700402",
      location: "England",
      address1: "14 Wharton Avenue",
      address2: "Thornton-Clevelys",
      address3: "Lancashire",
      address4: "",
      postCode: "FY5 4DQ",
      sortCode: "77-26-08",
      accountNo: "16032360",
      retainedClient: false,
      gender: "M",
      notes: "Warm, Informal, Quick to respond, Quite savvy, Comprehends things well, Splurge, Open to ideas"
    },
    {
      "Id": "FBAF2325-778C-478B-9F33-1CBBC6609D81",
      realName: "Michael Evans",
      penName: "Michael Evans",
      email: "michael.evans@the-times.co.uk",
      phoneNumber: "07768 081797",
      location: "England",
      address1: "1, Percival Road",
      address2: "London",
      address3: "",
      address4: "",
      postCode: "SW14 7QE",
      sortCode: "09-01-28",
      accountNo: "49600688",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "BEFF9546-1E59-4587-B848-1E9AC3FBAECD",
      realName: "Dannika Kendall",
      penName: "D.E. Kendall",
      email: "x_danni_x1@msn.com",
      phoneNumber: "07932478104",
      location: "Wales",
      address1: "259, Bryn Celyn",
      address2: "Pentwyn",
      address3: "Cardiff",
      address4: "",
      postCode: "CF23 7EN",
      sortCode: "20-18-17",
      accountNo: "53901408",
      retainedClient: false,
      gender: "F",
      notes: "Warm, Informal, Usually quick to respond, Not too savvy, Comprehends things well, Saver, Open to ideas"
    },
    {
      "Id": "B0622790-6995-4DC4-A5D9-1F11CEE1F729",
      realName: "Anthony Osae-Brown",
      penName: "Anthony Osae-Brown",
      email: "osaebrown@yahoo.com",
      phoneNumber: "234 8023165438",
      location: "Nigeria",
      address1: "PO Box 74544",
      address2: "V.I. Lagos",
      address3: "",
      address4: "",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: true,
      gender: "M",
      notes: ""
    },
    {
      "Id": "11DD239B-F9C5-425A-BD15-1F2C87E11718",
      realName: "Kathy Marker",
      penName: "Kathy Marker",
      email: "fmarker@safelink.net",
      phoneNumber: "208-312-7309 ",
      location: "United States",
      address1: "534 Malta Avenue",
      address2: "Burley",
      address3: "Idaho",
      address4: "",
      postCode: "83318",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "33BD8651-7C0C-43F3-B4F6-1F8775FB91BA",
      realName: "Paul Challis",
      penName: "P. G. Challis",
      email: "beaker@beakz.net",
      phoneNumber: "07770 274949, 01487 812839",
      location: "England",
      address1: "11, Royal Oak Close",
      address2: "Upwood",
      address3: "Ramsey",
      address4: "Cambs",
      postCode: "PE26 2AB",
      sortCode: "53-81-11",
      accountNo: "13014684",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "6819261A-8C39-42AD-B471-210100DBE13F",
      realName: "Christine Duts",
      penName: "Christine Duts",
      email: "chduts@gmail.com",
      phoneNumber: "",
      location: "Mexico",
      address1: "Calle Peotillos Mza 49 Lote 13",
      address2: "Monte Real",
      address3: "San Jose Del Cabo CP",
      address4: "B'aja California Sur",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: true,
      gender: "F",
      notes: ""
    },
    {
      "Id": "DBB34EEA-A5C5-4827-8A65-282CF4E87A90",
      realName: "Peter David Hull",
      penName: "Peter Hull",
      email: "peterdhull@talktalk.net",
      phoneNumber: "01458259292",
      location: "England",
      address1: "Arlington House",
      address2: "Bow Street",
      address3: "Langport",
      address4: "Somerset",
      postCode: "TA109PO",
      sortCode: "20-99-40",
      accountNo: "80504459",
      retainedClient: true,
      gender: "M",
      notes: "Warm, Quick to respond, Splurge, Open to ideas, Not too savvy"
    },
    {
      "Id": "E55C56BF-FFB4-4B3B-8C19-2D3CFAD19165",
      realName: "Luke Sutton",
      penName: "Luke Sutton",
      email: "suttonluke40@gmail.com",
      phoneNumber: "07927026300",
      location: "Wales",
      address1: "15, Hillcrest",
      address2: "Penley",
      address3: "Wrexham",
      address4: "",
      postCode: "LL13 0NL",
      sortCode: "40-47-26",
      accountNo: "72155168",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "6F37A078-6BF2-4539-A0BC-2DE3824AD82B",
      realName: "Matthew Gilbert",
      penName: "Matthew Gilbert",
      email: "mattgilbertwales@yahoo.com",
      phoneNumber: "07779091995",
      location: "Wales",
      address1: "27, Cross Acre",
      address2: "West Cross",
      address3: "Swansea",
      address4: "",
      postCode: "SA3 5NW",
      sortCode: "40-64-20",
      accountNo: "10458394",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "02FB236B-F857-40C7-ADD8-34500B2F9C02",
      realName: "Lakhbinder Singh Loi",
      penName: "Lak Loi",
      email: "auraleisure@yahoo.com, lak@auraleisure.com",
      phoneNumber: "0795 180 7982",
      location: "England",
      address1: "6, Danesbury Park",
      address2: "North Ride",
      address3: "Welwyn",
      address4: "Hertfordshire",
      postCode: "AL6 9SA",
      sortCode: "40-05-30",
      accountNo: "52785285",
      retainedClient: false,
      gender: "M",
      notes: ""
    }, {
      "Id": "E9D90110-8FD2-4D48-B590-37B09F07",
      realName: "J. F. Cicci",
      penName: "J. F. Cicci",
      email: "jfcicci@live.com",
      phoneNumber: "",
      location: "United States",
      address1: "1517 10th St N",
      address2: "Fargo",
      address3: "ND 58102",
      address4: "",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "2E989FE7-6F6F-457E-9BAC-38DBF26678B2",
      realName: "Gerald Keith Edmondson",
      penName: "Keith Edmondson",
      email: "g.edmondson@virgin.net",
      phoneNumber: "01274 612730",
      location: "England",
      address1: "40, Willow Crescent",
      address2: "Bradford",
      address3: "West Yorkshire",
      address4: "",
      postCode: "BD2 1LR",
      sortCode: "11-00-82",
      accountNo: "01965908",
      retainedClient: true,
      gender: "M",
      notes: ""
    },
    {
      "Id": "DA2A0890-E91B-4DF9-AF2D-3B6347F2ABD8",
      realName: "Heather Jones",
      penName: "Heather Jones",
      email: "heather_n_jones@hotmail.com",
      phoneNumber: "01244 537430",
      location: "Wales",
      address1: "6, Railway Terrace",
      address2: "Sandycroft",
      address3: "Deeside",
      address4: "Flintshire",
      postCode: "CH5 2QF",
      sortCode: "09-01-26",
      accountNo: "79836282",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "CF6E5C2D-5339-4EC4-9E06-42407FEE6066",
      realName: "Tracey Odessa Kane",
      penName: "Tracey Odessa Kane",
      email: "tkane176@gmail.com, philipkane@phonecoop.coop",
      phoneNumber: "01204 528616, 07707834704",
      location: "England",
      address1: "52, Silverwell Street",
      address2: "Bolton",
      address3: "", address4: "",
      postCode: "BL1 1PP",
      sortCode: "07-01-16",
      accountNo: "11687273",
      retainedClient: true,
      gender: "F",
      notes: ""
    },
    {
      "Id": "82CAFCA9-021E-4CEC-803B-494FB1A81B23",
      realName: "Sadhek Ahmed Khan",
      penName: "S. A. Khan",
      email: "sadhek@hotmail.com",
      phoneNumber: "07984 018 315",
      location: "England",
      address1: "3 Damien Court",
      address2: "Damien Street",
      address3: "London",
      address4: "E1 2HL",
      postCode: "",
      sortCode: "20-57-06",
      accountNo: "80365424",
      retainedClient: false,
      gender: "M",
      notes: "Warm but professional, can be slow to respond, not very savvy, likes to save money"
    },
    {
      "Id": "BD022B1A-D4EE-44B4-82FC-4AA60C4A9A2A",
      realName: "Bas Bastinck",
      penName: "B.",
      email: "nennius@planet.nl",
      phoneNumber: "",
      location: "The Netherlands",
      address1: "Frankrijklaan 37",
      address2: "1966 VC Heemskerk",
      address3: "",
      address4: "",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: true,
      gender: "M",
      notes: ""
    },
    {
      "Id": "18B8C471-4331-4192-AD8E-4AABFB0985AC",
      realName: "n o o n e",
      penName: "n o o n e",
      email: "chrisnoone@hotmail.co.uk",
      phoneNumber: "07990 594 449",
      location: "England",
      address1: "71, Spencer Street",
      address2: "Accrington",
      address3: "Lancashire",
      address4: "",
      postCode: "BB5 6ST",
      sortCode: "20-47-61",
      accountNo: "60550388",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "2BE058BD-83BE-4F3D-A95D-4D4368B1568D",
      realName: "Elijiah Pitman",
      penName: "Elijiah Pitman",
      email: "elijiahp @gmail.com; me @davidpitman.name",
      phoneNumber: " + 1(970) 268 - 5548",
      location: "Australia",
      address1: "30, Malvern Street",
      address2: "Salisbury",
      address3: "Queensland 4107",
      address4: "",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "C07A4EF1-B45A-41ED-A526-4EB1940ACAD3",
      realName: "Chris Rasmussen",
      penName: "Chris Rasmussen",
      email: "cjrmd3 @aol.com",
      phoneNumber: "(262) 219 - 6329",
      location: "USA",
      address1: "701 Westminster Drive",
      address2: "Waukesha",
      address3: "Wisconsin",
      address4: "53186 - 6648",
      postCode: "",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "F32E797A - 6485 - 4BE2 - BA58 - 4EC84628050A",
      realName: "David West",
      penName: "David West",
      email: "davidwest22@talktalk.net",
      phoneNumber: "01685 723028",
      location: "Wales",
      address1: "Monkton,",
      address2: "22, The Walk",
      address3: "Merthyr Tydfil",
      address4: "",
      postCode: "CF47 8RS", sortCode: "30-91-18", accountNo: "00471299", "CompanyId": "5B2E43B7-287B-4355-B26E-F26FA57C8D09", retainedClient: false, gender: "M", notes: ""
    },
    {
      "Id": "9E273739-148F-4D7A-88E7-4FCFF0EC9BCD",
      realName: "Erica Willmott",
      penName: "Erica Willmott",
      email: "ericawillmott79@yahoo.co.uk",
      phoneNumber: "07890222050",
      location: "Wales",
      address1: "85, Tyn-y-parc Road",
      address2: "Rhwbina",
      address3: "Cardiff",
      address4: "",
      postCode: "CF14 6BJ",
      sortCode: "40-16-15",
      accountNo: "01714457",
      retainedClient: true,
      gender: "F",
      notes: "Warm, Informal, Quick to respond, Not overly savvy, Comprehends things well, Splurge, Open to ideas"
    },
    {
      "Id": "E68B03FB-E605-4B3F-B620-51E987BA6ED7",
      realName: "Barbara Whetton",
      penName: "Barbara Whetton",
      email: "b_whetton@yahoo.com",
      phoneNumber: "07528892095",
      location: "England",
      address1: "39, Alloa Road",
      address2: "London",
      address3: "",
      address4: "",
      postCode: "SE85AH",
      sortCode: "20-70-70",
      accountNo: "50430293",
      retainedClient: true,
      gender: "F",
      notes: ""
    },
    {
      "Id": "FAE4C474-B89E-496D-BA0E-56AC7AF9FF4C",
      realName: "Joyce Maidment",
      penName: "Joyce Maidment",
      email: "joycelb@sky.com",
      phoneNumber: "01656 856880",
      location: "Wales",
      address1: "43, Wordsworth Avenue",
      address2: "Bridgend",
      address3: "",
      address4: "",
      postCode: "CF31 4SB",
      sortCode: "30-91-18",
      accountNo: "00845792",
      retainedClient: true,
      gender: "F",
      notes: "Warm, Informal, Slow repsonse, Not savvy, Things may need repeating, Splurge, Open to ideas"
    }, {
      "Id": "ACC2D680-6AEA-4DA5-BBBD-5CA2C791E9D8",
      realName: "Danny Marshall",
      penName: "Danny Marshall",
      email: "contact@dannymarshallwrites.com",
      phoneNumber: "",
      location: "England",
      address1: "The Nook",
      address2: "Crow Point",
      address3: "Halifax",
      address4: "West Yorkshire",
      postCode: "HX3 6UE",
      sortCode: "11-00-01",
      accountNo: "6262747",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "A67E4D55-86E5-4319-B5C1-60C763BAB197",
      realName: "Lewis Evans",
      penName: "Lewis Evans",
      email: "leme@btinternet.com",
      phoneNumber: "07484292100",
      location: "Wales",
      address1: "38, Ynys-Yr-Afon",
      address2: "Clyne",
      address3: "Neath",
      address4: "",
      postCode: "SA11 4BP",
      sortCode: "11-05-43",
      accountNo: "01080628",
      retainedClient: false,
      gender: "M",
      notes: "Warm, Informal, Quite responsive, Average savviness, Comprehends things quickly, Flush, Open to ideas"
    },
    {
      "Id": "8EE21430-FD2A-478A-8D02-64AA9956B3A0",
      realName: "Thomas Kerr",
      penName: "Thomas Kerr",
      email: "tom@tomkerr.co.uk",
      phoneNumber: "0131 441 1280",
      location: "Scotland",
      address1: "9, Woodhall Grove",
      address2: "Edinburgh",
      address3: "",
      address4: "",
      postCode: "EH13 0HR",
      sortCode: "83-26-10",
      accountNo: "00186079",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "34CB7F0F-1F33-49E5-8680-67D0AEACCA7C",
      realName: "Serena Diss",
      penName: "Serena Diss",
      email: "deamorrissey@aol.com",
      phoneNumber: "01492 584755, 07941608087",
      location: "England",
      address1: "15, Cambridge Road",
      address2: "Hale",
      address3: "Altrincham",
      address4: "Cheshire",
      postCode: "WA15 9SY",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "EC7FDCD7-7C64-4597-8496-686B33C4CFF8",
      realName: "Sian Jones & Jan Harvey",
      penName: "Harvey Jones",
      email: "jones.s38@sky.com, jan_harvey@hotmail.com",
      phoneNumber: "01446 745257, 07866 754924, 07790076993",
      location: "Wales",
      address1: "13, Taf Close,",
      address2: "Barry, CF62 7QU",
      address3: "12, Abingdon St,",
      address4: "Barry",
      postCode: "",
      sortCode: "40-16-15, 30-90-52",
      accountNo: "52843528, 25427460",
      retainedClient: true,
      gender: "F",
      notes: ""
    },
    {
      "Id": "5EA51B3F-FDBA-47DA-BCF8-6A3A90FAC800",
      realName: "Lance Barnwell",
      penName: "Lance Barnwell",
      email: "barnwell910@hotmail.co.uk",
      phoneNumber: "",
      location: "England",
      address1: "3A North Street",
      address2: "Asfordby Valley",
      address3: "Melton Mowbray",
      address4: "Leicesterhsire",
      postCode: "LE14 3SO",
      sortCode: "77 - 15 - 18",
      accountNo: "07832668",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "A40184C0-6CE8-484F-9F0E-6A5D8D79F622",
      realName: "David Ward",
      penName: "David Ward",
      email: "d.ward01@btinternet.com",
      phoneNumber: "", location: "",
      address1: "",
      address2: "",
      address3: "",
      address4: "",
      postCode: "",
      sortCode: "60 - 07 - 39",
      accountNo: "56348703",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "A323FDC7 - 181D - 4887 - A994 - 6BCAC2A47302",
      realName: "George Learmonth",
      penName: "George Learmonth",
      email: "agricola @supanet.com",
      phoneNumber: "01547 529060 ",
      location: "Wales",
      address1: "3, Market Street",
      address2: "Knighton",
      address3: "Powys",
      address4: "LD7 1EY",
      postCode: "",
      sortCode: "07 - 01 - 16",
      accountNo: "09364343",
      retainedClient: false,
      gender: "M", notes: ""
    },
    {
      "Id": "C78E9211 - DCAB - 4443 - A9E4 - 6F4488BB34CF",
      realName: "Jacqueline Ellery",
      penName: "Jacqueline Anne",
      email: "jacqueline.ellery@gmail.com",
      phoneNumber: "07786658208",
      location: "Wales",
      address1: "244, The Hawthorns",
      address2: "Pentwyn",
      address3: "Cardiff",
      address4: "",
      postCode: "CF23 7AU",
      sortCode: "40 - 13 - 23",
      accountNo: "61612115",
      retainedClient: true,
      gender: "F",
      notes: "Warm, Informal, Middling response time, Fairly savvy, Comprehends things well, Saver - but reasonable, Not picky"
    },
    {
      "Id": "ACCDE42A - 3C66 - 4717 - 9ECD - 719AFFBDBB03",
      realName: "S.A.Burgess",
      penName: "S.A.Burgess",
      email: "songofsteel @hotmail.com",
      phoneNumber: "01226 643424",
      location: "England",
      address1: "98, Wilson Street",
      address2: "Wombwell",
      address3: "Barnsley",
      address4: "South Yorkshire",
      postCode: "S73 8RD",
      sortCode: "51 - 61 - 35",
      accountNo: "75505800",
      retainedClient: true,
      gender: "M",
      notes: ""
    },
    {
      "Id": "D75DA827 - 6DDD - 4A40 - A81A - 725B813AD8E3",
      realName: "Sarah Padget",
      penName: "Sarah Padget",
      email: " sarahpadget@gmail.com",
      phoneNumber: "01323848677",
      location: "England",
      address1: "7 The Croft",
      address2: "Lauer Dicker",
      address3: "East Sussex",
      address4: "",
      postCode: "BN274BS",
      sortCode: "07 - 01 - 16",
      accountNo: "31081808",
      retainedClient: false,
      gender: "F",
      notes: "Warm, Informal, Sometimes needs prompting, Not very savvy, Comprehends things well, Saver, Can be picky at times - wants the book to reflect her ideas \r\n\r\n"
    },
    {
      "Id": "09A885D1 - 00AB - 472C - B057 - 73E156C2DBA1",
      realName: "Chris Pridmore",
      penName: "Chris Pridmore",
      email: "chrispy46 @hotmail.com",
      phoneNumber: "07729972596",
      location: "Wales",
      address1: "12, Powys Road",
      address2: "Llandudno",
      address3: "LL30 1HZ",
      address4: "",
      postCode: "",
      sortCode: "09 - 01 - 28",
      accountNo: "60503764",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "A8965F36 - E45E - 4977 - B536 - 749B7ABF0E28",
      realName: "Amy Bench",
      penName: "Amy Bench",
      email: "a_m_y_bench @hotmail.co.uk",
      phoneNumber: "07581304058",
      location: "England",
      address1: "41, School Lane",
      address2: "Inskip",
      address3: "Preston",
      address4: "Lancashire",
      postCode: "PR4 0TS",
      sortCode: "09 - 01 - 27",
      accountNo: "42992613",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "8972F332 - 6827 - 4384 - A715 - 76B8788C4604",
      realName: "Zaina Budaly",
      penName: "Z.R.Ghani",
      email: "zainabudaly33 @gmail.com",
      phoneNumber: "07473 700100",
      location: "England",
      address1: "70, Victoria Road",
      address2: "Edmonton",
      address3: "London",
      address4: "",
      postCode: "N9 9SU",
      sortCode: "20 - 53 - 00",
      accountNo: "13772217",
      retainedClient: false,
      gender: "F",
      notes: ""
    },
    {
      "Id": "2F314D69-FC01-4956-B31B-78DBFCFB6ED0",
      realName: "James Williamson",
      penName: "James Williamson",
      email: "tony_j_delaney@yahoo.co.uk",
      phoneNumber: "",
      location: "England",
      address1: "5, Dunlin Court",
      address2: "Albion Terrace",
      address3: "Lynemouth",
      address4: "Northumberland",
      postCode: "NE61 5SY",
      sortCode: "",
      accountNo: "",
      retainedClient: false,
      gender: "M",
      notes: ""
    },
    {
      "Id": "B7522A65-8BA1-4653-BC15-80CC4CEF6FD3",
      realName: "Warren Jones",
      penName: "Poisoned Rats",
      email: "Wozandcarly@hotmail.co.uk",
      phoneNumber: "07415779400",
      location: "England",
      address1: "59, Rydal Road",
      address2: "Helmshore",
      address3: "Rossendale",
      address4: "",
      postCode: "BB4 4EF",
      sortCode: "30-96-68",
      accountNo: "4532381",
      retainedClient: false,
      gender: "M",
      notes: "Warm, Informal, Very responsive, Not very savvy, Grasps things first time, Stringent, Can be picky (on editorial content mainly)"
    },
    {
      "Id": "A66F5045-6243-44FE-AC9B-8284C18DD8E4",
      realName: "Scott Hamill",
      penName: "Scott Hamill",
      email: "s.hamill@lancaster.ac.uk",
      phoneNumber: "07591449232",
      location: "Scotland",
      address1: "15 17 Hawkhill Close",
      address2: "",
      address3: "",
      address4: "Edinburgh",
      postCode: "EH7 6AL",
      sortCode: "98-11-30",
      accountNo: "10275307",
      retainedClient: true,
      gender: "M",
      notes: ""
    },
    {
      "Id": "BA9368D3-A54E-488D-A4AA-82999668007C",
      realName: "Ben Cole-Edwards",
      penName: "Ben Cole-Edwards",
      email: "ben.coleedwards@rocketmail.com",
      phoneNumber: "07456876551",
      location: "Wales",
      address1: "12, Heol y Bryn",
      address2: "Llangynwyd",
      address3: "Maesteg",
      address4: "Cardiff",
      postCode: "CF34 9SY",
      sortCode: "53-81-27 ",
      accountNo: "85080551",
      retainedClient: true,
      gender: "M",
      notes: "Warm, Informal, Quick to respond,Fairly savvy, Comprehends things well, Saver, Open to ideas"
    }
  ]

